extends:
  - jason/react
  - eslint-config-4catalyzer-typescript
  - prettier
globals:
  css: false
rules:
  global-require: 0
  quotes: 0
  no-unused-expressions: 0
  prefer-const: off
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/no-use-before-define": off
